apiVersion: v1
kind: Service
metadata:
  name: {{ include "srs.fullname" . }}
  labels:
    {{- include "srs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rtmp
      port: {{ .Values.service.rtmp }}
      targetPort: 1935
      protocol: TCP
    - name: http
      port: {{ .Values.service.http }}
      targetPort: 2022
      protocol: TCP
    - name: https
      port: {{ .Values.service.https }}
      targetPort: 2443
      protocol: TCP
    - name: srt
      port: {{ .Values.service.srt }}
      targetPort: 10080
      protocol: UDP
    - name: rtc
      port: {{ .Values.service.rtc }}
      targetPort: 8000
      protocol: UDP
  selector:
    {{- include "srs.selectorLabels" . | nindent 4 }}
